### ISSUE TITLE
Reverse date difference

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#24]
Date difference shows weird results when the second date is before the first.

![Screenshot from 2020-02-29 10-29-24](https://user-images.githubusercontent.com/25565229/75604959-5dbb0a80-5ade-11ea-8a4c-9d6195b995fe.png)

Also, a "swap" button would be nice here.

**Comment by SubhadeepJasu** [comment]
So should I get rid of the "-" sign, so its just a difference?
Its a difficult decision because of how they are labelled as "from" and "to", and technically "from" should be before "to", but you have option to do the opposite.

Which also means that I have to change "from" and "to" to something like "date 1" and "date 2" and then a swap button becomes irrelevant. I would ask someone for advice on this.

**Comment by SubhadeepJasu** [comment]
I might implement something like auto swap the two.

**Comment by SubhadeepJasu** [comment]
Fixed
