### ISSUE TITLE
Wrong decimal/thousands separators

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#44]
I don't know if it's a bug or a locale I'm unfamiliar with, but decimal and thousands separators are totally messed up for me. The decimal separator is a double comma, thousands separators are sometimes every two digits instead of three. My machine's locale is set like this:

![Screenshot from 2020-03-29 00 22 07](https://user-images.githubusercontent.com/25565229/77836094-63deee00-7153-11ea-83bb-38e2e130bdfb.png)

so numbers should be formatted with a decimal point and a comma every three digits. Now have a look at these examples:

![Screenshot from 2020-03-29 00 17 08](https://user-images.githubusercontent.com/25565229/77836056-0c408280-7153-11ea-8b27-a07bf8154f64.png)
(should be 3.141,59265359)

![Screenshot from 2020-03-29 00 17 20](https://user-images.githubusercontent.com/25565229/77836057-0d71af80-7153-11ea-9244-cf6590ec18c0.png)
(should be 100)

![Screenshot from 2020-03-29 00 17 50](https://user-images.githubusercontent.com/25565229/77836058-0d71af80-7153-11ea-966e-c961a4bbae29.png)
(should be 123.456.789)

![Screenshot from 2020-03-29 00 18 40](https://user-images.githubusercontent.com/25565229/77836059-0d71af80-7153-11ea-8cbc-d3ee1744af63.png)
(should be 123,456)

**Comment by javogarcia** [comment]
Same issue here. Download the app recently and was surprised! What's supposed to be the meaning of this? (image below)

![Captura de pantalla de 2020-04-28 22-26-38](https://user-images.githubusercontent.com/17933209/80553437-3a0e2680-89a0-11ea-91e8-e410b370ce9a.png)

Please somebody fix it 🙏️

**Comment by jgomer2001** [comment]
Faced something similar. I had to change the format to "United states" so that `.` is used as a decimal separator and  `,` separates thousands. In my country we use different rules but I have to recognize this form of separators gives trouble (not only in Elementary OS) with  applications such as spreadsheets.

To change format search for "language and region", and you'll see a dropdown. For changes to take effect, logout is required I guess
